Repository thoth-station/user-api, pull requests merged in 2018-04, with the labels that each got.

#81 Remove dependencies.yaml
  dependencies.yml
Labels: approved

#80 Introduce force sync options
  thoth_user_api/api_v1.py
  thoth_user_api/swagger.yaml
  thoth_user_api/utils.py
Labels: approved

#83 Return 404 if the given document was not found
  thoth_user_api/api_v1.py
Labels: approved

#85 Provide an option to disable TLS cert verification in analyzer
  thoth_user_api/api_v1.py
  thoth_user_api/swagger.yaml
  thoth_user_api/utils.py
Labels: approved

#86 Add missing argument for transitive dependencies scan
  thoth_user_api/api_v1.py
Labels: approved

#79 Place /sync endpoint to admin section
  thoth_user_api/swagger.yaml
Labels: approved

#87 humans: let's reclaim our mattermost channel
  Jenkinsfile
Labels: approved

#88 adding the OWNERS file
  OWNERS
Labels: approved, size/XS

#89 Remove thoth- prefix
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
Labels: approved, size/S

#90 Use path parameters instead of query where appropriate
  thoth_user_api/swagger.yaml
Labels: size/XS

#91 License and license headers
  LICENSE
  thoth_user_api/api_v1.py
  thoth_user_api/configuration.py
  thoth_user_api/entrypoint.py
  thoth_user_api/parsing/handlers/base.py
  thoth_user_api/parsing/handlers/dnf.py
  thoth_user_api/parsing/handlers/pip.py
  thoth_user_api/parsing/handlers/pip3.py
  thoth_user_api/parsing/handlers/yum.py
  thoth_user_api/utils.py
Labels: approved, size/XXL

#94 Fix graph sync endpoint
  thoth_user_api/utils.py
Labels: approved, size/M

#92 List runtime environments endpoint
  Pipfile
  Pipfile.lock
  thoth_user_api/api_v1.py
  thoth_user_api/swagger.yaml
Labels: approved, size/L

#97 Fix wrong argument for pagination
  thoth_user_api/api_v1.py
Labels: approved, size/XS

#98 Remove the /run endpoint
  thoth_user_api/api_v1.py
  thoth_user_api/swagger.yaml
  thoth_user_api/utils.py
Labels: approved, size/M

#100 Do not restrict image names on API
  thoth_user_api/swagger.yaml
Labels: approved, component/analyser, size/XS
