Repository thoth-station/user-api, pull requests merged in 2018-09, with the labels that each got.

#204 Automatic update of dependency attrs from 18.1.0 to 18.2.0
  Pipfile.lock
Labels: bot

#206 Automatic update of dependency thoth-storages from 0.5.1 to 0.5.2
  Pipfile.lock
Labels: bot

#207 Automatic update of dependency thoth-common from 0.2.5 to 0.2.6
  Pipfile.lock
Labels: bot

#208 Automatic update of dependency thoth-common from 0.2.6 to 0.2.7
  Pipfile.lock
Labels: bot

#205 Provide frontend namespace configuration
  openshift/deployment-template.yaml
Labels: size/XS

#194 Introduce provenance endpoint
  thoth_user_api/api_v1.py
  thoth_user_api/configuration.py
  thoth_user_api/swagger.yaml
Labels: size/M, size/S

#213 Refactoring
  thoth_user_api/api_v1.py
  thoth_user_api/swagger.yaml
Labels: approved, size/L

#214 Fix method name
  thoth_user_api/api_v1.py
Labels: approved, size/XS

#216 Remove accidentally duplicated function
  thoth_user_api/api_v1.py
Labels: approved, size/S

#218 Refactor API to reflect current functionality
  thoth_user_api/api_v1.py
  thoth_user_api/configuration.py
  thoth_user_api/swagger.yaml
Labels: approved, size/XL

#220 Fix parameter name
  thoth_user_api/swagger.yaml
Labels: approved, size/XS

#221 Automatic update of dependency thoth-common from 0.2.7 to 0.3.0
  Pipfile.lock
Labels: bot

#219 Translate timeout to user
  thoth_user_api/api_v1.py
  thoth_user_api/swagger.yaml
Labels: size/M, size/XL

#230 Automatic update of dependency pytest from 3.7.4 to 3.8.0
  Pipfile.lock
Labels: bot

#224 Fix built-in type shadowing
  thoth_user_api/api_v1.py
  thoth_user_api/swagger.yaml
Labels: approved, size/XS

#227 Expose provenance debug option on API
  thoth_user_api/swagger.yaml
Labels: approved, size/XS

#229 Rename recommend to advise all over the places
  thoth_user_api/api_v1.py
  thoth_user_api/swagger.yaml
Labels: approved, size/M

#238 Automatic update of dependency connexion from 1.5.2 to 1.5.3
  Pipfile.lock
Labels: bot

#241 Remove underscore in cotainer name in response
  thoth_user_api/api_v1.py
  thoth_user_api/swagger.yaml
Labels: size/XS

#243 Container SHA can be null when analysis is pending
  thoth_user_api/swagger.yaml
Labels: size/XS

#240 Fix parameter name
  thoth_user_api/api_v1.py
Labels: size/XS

#244 Automatic update of dependency thoth-common from 0.3.0 to 0.3.1
  Pipfile.lock
Labels: bot

#245 Allow empty lock to be submitted
  thoth_user_api/swagger.yaml
Labels: approved, size/M, size/XS

#250 Remove 400 responses where not needed
  thoth_user_api/api_v1.py
Labels: approved, size/L

#254 Remove unused import
  thoth_user_api/api_v1.py
Labels: approved, size/XS

#255 Gathering status report moved to common
  thoth_user_api/api_v1.py
Labels: approved, size/M

#253 Fix retrieving documents on wrong endpoint
  thoth_user_api/api_v1.py
Labels: approved, size/M

#247 Provide custom error handlers with more information
  thoth_user_api/entrypoint.py
Labels: approved, size/S

#246 Fix analysis listing model
  thoth_user_api/swagger.yaml
Labels: approved, size/S

#236 Signalize user if no solvers were run
  thoth_user_api/api_v1.py
Labels: approved, size/S

#259 Revert "Add a Codacy badge to README.rst"
  README.rst
Labels: size/XS

#263 Automatic update of dependency thoth-common from 0.3.1 to 0.3.2
  Pipfile.lock
Labels: bot

#262 State nullable values in swagger
  thoth_user_api/swagger.yaml
Labels: approved, size/M

#265 Automatic update of dependency thoth-common from 0.3.5 to 0.3.6
  Pipfile.lock
Labels: bot
