Repository thoth-station/user-api, pull requests merged in 2018-07, with the labels that each got.

#135 Automatic update of dependency thoth-common from 0.0.7 to 0.0.9
  Pipfile.lock
Labels: approved, bot, size/M

#138 Issue/137
  openshift/deployment-template.yaml
Labels: approved, size/XS

#141 Automatic update of dependency thoth-storages from 0.0.32 to 0.0.33
  Pipfile.lock
Labels: approved, bot, size/XS

#143 Use service account token function from thoth-common
  thoth_user_api/configuration.py
Labels: approved, size/S

#144 Update deployment-template.yaml
  openshift/deployment-template.yaml
Labels: approved, size/S

#142 removed some E501, as the max line lenght is 120 now!
  .coafile
  thoth_user_api/utils.py
Labels: approved, size/M

#147 removed pydocstyle
  Pipfile
Labels: approved, bot

#148 Automatic update of dependency thoth-common from 0.0.9 to 0.1.0
  Pipfile.lock
Labels: bot

#149 Automatic update of dependency pytest from 3.6.2 to 3.6.3
  Pipfile.lock
Labels: approved, bot

#151 Automatic update of dependency thoth-common from 0.1.0 to 0.2.0
  Pipfile.lock
Labels: bot

#153 Initial dependency lock
  Pipfile.lock
Labels: bot

#154 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#155 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#156 Automatic update of dependency thoth-common from 0.2.0 to 0.2.1
  Pipfile.lock
Labels: bot

#127 Update utils.py
  thoth_user_api/utils.py
Labels: size/XS

#157 Automatic update of dependency pylint from 1.9.2 to 2.0.0
  Pipfile.lock
Labels: bot

#114 Introduce initial recommendation endpoints
  thoth_user_api/api_v1.py
  thoth_user_api/swagger.yaml
Labels: do-not-merge/work-in-progress, size/M

#160 Automatic update of dependency thoth-storages from 0.0.33 to 0.1.0
  Pipfile.lock
Labels: bot

#159 changes in JSON format to add another variable
  thoth_user_api/swagger.yaml
Labels: approved

#163 Automatic update of dependency connexion from 1.4.2 to 1.5.1
  Pipfile.lock
Labels: bot

#165 Automatic update of dependency pytest-timeout from 1.3.0 to 1.3.1
  Pipfile.lock
Labels: bot

#162 increasing the requested resources
  openshift/buildConfig-template.yaml
Labels: approved

#169 Automatic update of dependency connexion from 1.5.1 to 1.5.2
  Pipfile.lock
Labels: bot

#170 Automatic update of dependency thoth-storages from 0.1.0 to 0.1.1
  Pipfile.lock
Labels: bot

#171 Automatic update of dependency pytest from 3.6.3 to 3.6.4
  Pipfile.lock
Labels: bot

#173 Automatic update of dependency thoth-common from 0.2.1 to 0.2.2
  Pipfile.lock
Labels: bot

#168 Disable HTTP request logs
  thoth_user_api/entrypoint.py
Labels: approved

#174 Increase memory otherwise container exits on os error 14
  openshift/deployment-template.yaml
Labels: approved, size/XS

#175 Automatic update of dependency pytest from 3.6.4 to 3.7.0
  Pipfile.lock
Labels: bot
