Repository thoth-station/user-api, pull requests merged in 2018-12, with the labels that each got.

#360 Introduce cache in provenance checks
  Pipfile
  Pipfile.lock
  thoth/user_api/api_v1.py
  thoth/user_api/configuration.py
Labels: approved, size/L, size/M, size/XL

#365 Automatic update of dependency prometheus-client from 0.4.2 to 0.5.0
  Pipfile.lock
Labels: bot

#366 Automatic update of dependency prometheus-flask-exporter from 0.4.0 to 0.4.1
  Pipfile.lock
Labels: bot

#367 Automatic update of dependency requests from 2.20.1 to 2.21.0
  Pipfile.lock
Labels: bot

#370 Avoid circular JSONs on error response
  thoth/user_api/api_v1.py
Labels: size/S

#371 Cache should also distinguish recommendation type
  thoth/user_api/api_v1.py
Labels: size/XS
