Repository thoth-station/user-api, pull requests merged in 2018-05, with the labels that each got.

#102 we dont use travis-ci at this moment
  .travis.yml
Labels: approved, size/XS

#105 Update storages
  Pipfile
  Pipfile.lock
  thoth_user_api/parsing/handlers/__pycache__/__init__.cpython-36.pyc
  thoth_user_api/parsing/handlers/__pycache__/base.cpython-36.pyc
  thoth_user_api/parsing/handlers/__pycache__/dnf.cpython-36.pyc
  thoth_user_api/parsing/handlers/__pycache__/pip3.cpython-36.pyc
  thoth_user_api/parsing/handlers/__pycache__/yum.cpython-36.pyc
Labels: approved, size/L

#106 Run Coala in CI
  .travis.yml
Labels: size/XS

#107 Test to trigger CI
  README.rst
Labels: size/XS

#108 Extend liveness probe with Ceph connection check
  thoth_user_api/entrypoint.py
Labels: approved, size/S

#110 Add rsyslog logging
  openshift/deployment-template.yaml
  thoth_user_api/utils.py
Labels: size/S

#111 Update thoth-common for rsyslog logging
  Pipfile
  Pipfile.lock
Labels: approved, size/M
