Repository thoth-station/user-api, pull requests merged in 2018-11, with the labels that each got.

#316 Provenance checks will be cached as well
  thoth_user_api/api_v1.py
Labels: approved, size/XS

#310 Fix key error when gathering pod status
  thoth_user_api/api_v1.py
Labels: approved, size/XS

#312 Implement caching of package-extract results
  thoth_user_api/api_v1.py
Labels: size/M

#321 Clear unused dependencies
  Pipfile
  Pipfile.lock
Labels: size/L

#323 using thoth zuul jobs now
  .zuul.yaml
  thoth/user_api/api_v1.py
Labels: size/XS

#320 Frontend namespace is set from configmap
  openshift/deployment-template.yaml
Labels: approved, size/XS

#322 Remove endpoints that were moved to management API
  openshift/deployment-template.yaml
  thoth/user_api/api_v1.py
  thoth/user_api/configuration.py
  thoth/user_api/swagger.yaml
Labels: approved, size/L

#327 Automatic update of dependency pytest from 3.9.3 to 3.10.0
  Pipfile.lock
Labels: bot

#328 OpenShift are not markers but extras
  Pipfile.lock
Labels: size/XS

#330 Automatic update of dependency thoth-common from 0.3.16 to 0.4.0
  Pipfile.lock
Labels: bot

#303 Job that will redeploy user-api
  .zuul.yaml
  devops_push_image.yaml
  devops_redeploy.yaml
Labels: approved, size/L, size/M, size/S

#334 New connexion requires swagger-ui extras
  Pipfile
  Pipfile.lock
Labels: size/M

#337 Automatic update of dependency thoth-storages from 0.7.2 to 0.7.4
  Pipfile.lock
Labels: bot

#335 Automatic update of dependency connexion from 2.0.0 to 2.0.1
  Pipfile.lock
Labels: bot

#338 Automatic update of dependency thoth-storages from 0.7.4 to 0.7.5
  Pipfile.lock
Labels: bot

#339 Automatic update of dependency thoth-storages from 0.7.5 to 0.7.6
  Pipfile.lock
Labels: bot

#340 Automatic update of dependency requests from 2.20.0 to 2.20.1
  Pipfile.lock
Labels: bot

#341 Automatic update of dependency pytest from 3.10.0 to 3.10.1
  Pipfile.lock
Labels: bot

#343 Automatic update of dependency pytest from 3.10.1 to 4.0.0
  Pipfile.lock
Labels: bot

#344 Automatic update of dependency connexion from 2.0.1 to 2.0.2
  Pipfile.lock
Labels: bot

#345 Automatic update of dependency thoth-storages from 0.7.6 to 0.8.0
  Pipfile.lock
Labels: bot

#346 Automatic update of dependency thoth-common from 0.4.0 to 0.4.1
  Pipfile.lock
Labels: bot

#347 Automatic update of dependency thoth-common from 0.4.1 to 0.4.2
  Pipfile.lock
Labels: bot

#348 Automatic update of dependency thoth-common from 0.4.2 to 0.4.3
  Pipfile.lock
Labels: bot

#351 Automatic update of dependency thoth-common from 0.4.3 to 0.4.4
  Pipfile.lock
Labels: bot

#350 Introduce count and limit on API for advise
  thoth/user_api/api_v1.py
  thoth/user_api/swagger.yaml
Labels: size/S

#355 Automatic update of dependency thoth-common from 0.4.4 to 0.4.5
  Pipfile.lock
Labels: bot

#356 Be more precise with swagger model examples
  thoth/user_api/swagger.yaml
Labels: size/XS

#359 Automatic update of dependency pytest from 4.0.0 to 4.0.1
  Pipfile.lock
Labels: bot

#361 Feature/metrics export
  Pipfile
  Pipfile.lock
  pyproject.toml
  thoth/user_api/entrypoint.py
Labels: approved, size/L

#363 Automatic update of dependency thoth-common from 0.4.5 to 0.4.6
  Pipfile.lock
Labels: bot
