Repository thoth-station/user-api, pull requests merged in 2018-08, with the labels that each got.

#176 Automatic update of dependency pylint from 2.0.1 to 2.1.0
  Pipfile.lock
Labels: bot

#177 Increase memory for user-api
  openshift/deployment-template.yaml
Labels: approved, size/XS

#167 Use OpenShift as a naming service
  Pipfile
  thoth_user_api/api_v1.py
  thoth_user_api/configuration.py
  thoth_user_api/entrypoint.py
  thoth_user_api/exceptions.py
  thoth_user_api/swagger.yaml
  thoth_user_api/utils.py
Labels: approved, size/XL, size/XXL

#179 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XL

#181 Tweak running adviser
  thoth_user_api/swagger.yaml
  thoth_user_api/utils.py
Labels: size/S

#183 Automatic update of dependency thoth-storages from 0.1.1 to 0.2.0
  Pipfile.lock
Labels: bot

#184 Automatic update of dependency thoth-storages from 0.2.0 to 0.3.0
  Pipfile.lock
Labels: bot

#185 Automatic update of dependency thoth-storages from 0.3.0 to 0.4.0
  Pipfile.lock
Labels: bot

#186 Automatic update of dependency thoth-storages from 0.4.0 to 0.5.0
  Pipfile.lock
Labels: bot

#188 Automatic update of dependency kubernetes from 6.0.0 to 7.0.0
  Pipfile.lock
Labels: bot

#182 Use OpenShift object from thoth-common
  Pipfile
  thoth_user_api/api_v1.py
  thoth_user_api/configuration.py
  thoth_user_api/utils.py
Labels: approved, size/L

#193 Automatic update of dependency pytest from 3.7.1 to 3.7.3
  Pipfile.lock
Labels: bot

#191 Automatic update of dependency thoth-storages from 0.5.0 to 0.5.1
  Pipfile.lock
Labels: bot

#197 OpenShift and K8s are no longer direct deps
  Pipfile
  Pipfile.lock
Labels: size/XL, size/XS

#198 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XL

#199 Automatic update of dependency pytest from 3.7.3 to 3.7.4
  Pipfile.lock
Labels: bot

#200 Automatic update of dependency thoth-common from 0.2.4 to 0.2.5
  Pipfile.lock
Labels: bot
