Repository thoth-station/user-api, pull requests merged in 2018-06, with the labels that each got.

#118 Rename THOTH_MIDDLEEND_NAMESPACE to THOTH_MIDDLETIER_NAMESPACE
  openshift/deployment-template.yaml
  thoth_user_api/configuration.py
  thoth_user_api/utils.py
Labels: approved, lgtm, size/M

#115 Added pagination info in response header
  thoth_user_api/api_v1.py
Labels: approved, lgtm, size/S

#121 set resource limits of BC, DC
  CHANGELOG.md
  README.rst
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  thoth_user_api/__init__.py
Labels: approved, lgtm, size/S

#123 Rename THOTH_CEPH_HOST to THOTH_S3_ENDPOINT_URL
  openshift/deployment-template.yaml
  thoth_user_api/utils.py
Labels: approved, lgtm, size/XS

#128 preparing for zuul
  .coafile
  .travis.yml
  .zuul.yaml
  CHANGELOG.md
  Jenkinsfile
  Pipfile
  Pipfile.lock
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  thoth_user_api/__init__.py
  thoth_user_api/api_v1.py
  thoth_user_api/configuration.py
  thoth_user_api/parsing/__init__.py
  thoth_user_api/parsing/handlers/__init__.py
  thoth_user_api/parsing/handlers/base.py
  thoth_user_api/parsing/handlers/dnf.py
  thoth_user_api/parsing/handlers/pip.py
  thoth_user_api/parsing/handlers/pip3.py
  thoth_user_api/parsing/handlers/yum.py
  thoth_user_api/swagger.yaml
  thoth_user_api/utils.py
Labels: approved, size/XXL

#130 Move resource definition for buildconfig to proper entry
  openshift/buildConfig-template.yaml
Labels: approved, size/S

#132 Added min length to swagger.yaml
  thoth_user_api/swagger.yaml
Labels: approved, size/XS
