Repository thoth-station/user-api, pull requests merged in 2018-10, with the labels that each got.

#266 Automatic update of dependency pytest from 3.8.1 to 3.8.2
  Pipfile.lock
Labels: bot

#267 Introduce dependency monkey endpoints
  thoth_user_api/api_v1.py
  thoth_user_api/swagger.yaml
Labels: approved, size/L, size/M

#270 Move from Pods to Jobs
  thoth_user_api/api_v1.py
Labels: approved, size/M

#272 Automatic update of dependency thoth-common from 0.3.6 to 0.3.7
  Pipfile.lock
Labels: bot

#274 Automatic update of dependency thoth-common from 0.3.7 to 0.3.8
  Pipfile.lock
Labels: bot

#275 Automatic update of dependency thoth-common from 0.3.8 to 0.3.9
  Pipfile.lock
Labels: bot

#276 split out the imagestream into his own template
  .gitignore
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#277 fixed the template name
  openshift/imageStream-template.yaml
Labels: size/XS

#273 Fix status gathering
  thoth_user_api/api_v1.py
Labels: approved, size/XS

#281 Automatic update of dependency thoth-common from 0.3.9 to 0.3.10
  Pipfile.lock
Labels: bot

#282 added THOTH_JANUSGRAPH_{HOST|POST} as template parameters
  openshift/deployment-template.yaml
Labels: approved, size/M

#280 Fix typo in argument name
  thoth_user_api/api_v1.py
Labels: approved, size/XS

#287 Automatic update of dependency thoth-storages from 0.5.3 to 0.5.4
  Pipfile.lock
Labels: bot

#283 using envvar that are injected by OpenShift
  openshift/deployment-template.yaml
Labels: approved, size/S

#279 Logs can be nullable
  thoth_user_api/swagger.yaml
Labels: size/XS

#289 Introduce cached results of analyses
  thoth_user_api/api_v1.py
  thoth_user_api/swagger.yaml
Labels: approved, size/M

#291 Respect dependency monkey output configuration
  thoth_user_api/api_v1.py
  thoth_user_api/configuration.py
Labels: approved, size/S

#292 Amun API is URL not host
  thoth_user_api/configuration.py
Labels: approved, size/XS

#293 Automatic update of dependency pytest from 3.8.2 to 3.9.1
  Pipfile.lock
Labels: bot

#294 Automatic update of dependency requests from 2.19.1 to 2.20.0
  Pipfile.lock
Labels: bot

#295 Automatic update of dependency thoth-common from 0.3.11 to 0.3.12
  Pipfile.lock
Labels: bot

#297 Automatic update of dependency pytest from 3.9.1 to 3.9.2
  Pipfile.lock
Labels: bot

#304 Automatic update of dependency thoth-common from 0.3.13 to 0.3.14
  Pipfile.lock
Labels: bot

#306 Do not propagate force to actual package-extract run
  thoth_user_api/api_v1.py
Labels: size/XS

#307 Automatic update of dependency thoth-common from 0.3.14 to 0.3.15
  Pipfile.lock
Labels: bot

#305 Do not propagate force to analysis run
  thoth_user_api/api_v1.py
Labels: approved, size/XS
