Repository thoth-station/user-api, pull requests merged in 2019-08, with the labels that each got.

#509 Automatic update of dependency thoth-storages from 0.18.0 to 0.18.1
  Pipfile.lock
Labels: bot

#510 Automatic update of dependency thoth-storages from 0.18.1 to 0.18.3
  Pipfile.lock
Labels: bot

#512 Remove anchors and use refs instead
  openapi/openapi.yaml
Labels: approved, size/S

#513 Enforce new invectio version by providing required schema
  openapi/openapi.yaml
Labels: approved, size/XS

#476 Kebechet
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/L, size/M

#511 Add information comming from Jupyter Notebooks
  openapi/openapi.yaml
Labels: approved, size/XS

#517 Automatic update of dependency thoth-common from 0.9.5 to 0.9.6
  Pipfile.lock
Labels: bot

#518 Automatic update of dependency thoth-storages from 0.18.3 to 0.18.4
  Pipfile.lock
Labels: bot

#519 Automatic update of dependency prometheus-flask-exporter from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot

#520 Start using Thoth in OpenShift's s2i
  .s2i/bin/assemble
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
Labels: size/M

#522 Automatic update of dependency thoth-python from 0.6.0 to 0.6.1
  Pipfile.lock
Labels: bot

#521 Automatic update of dependency thoth-storages from 0.18.4 to 0.18.5
  Pipfile.lock
Labels: bot

#523 Wrong URLs
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#526 Stop using extras in thoth-common
  Pipfile
  Pipfile.lock
Labels: size/XL

#528 Initial dependency lock
  Pipfile.lock
Labels: bot, size/XL

#527 Runtime environment is now reported on the project instance
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#529 Automatic update of dependency thoth-common from 0.9.7 to 0.9.8
  Pipfile.lock
Labels: bot

#530 Automatic update of dependency thoth-storages from 0.18.5 to 0.18.6
  Pipfile.lock
Labels: bot

#531 Kebechet conf
  .thoth.yaml
Labels: approved, size/S

#532 Provide endpoint for listing supported runtime environments
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M

#533 Automatic update of dependency grpcio from 1.22.0 to 1.22.1
  Pipfile.lock
Labels: bot

#535 Automatic update of dependency grpcio from 1.22.1 to 1.23.0
  Pipfile.lock
Labels: bot

#536 Automatic update of dependency grpcio-tools from 1.22.0 to 1.23.0
  Pipfile.lock
Labels: bot

#537 Automatic update of dependency pytest from 5.0.1 to 5.1.0
  Pipfile.lock
Labels: bot

#540 Automatic update of dependency pytest from 5.1.0 to 5.1.1
  Pipfile.lock
Labels: bot

#542 Automatic update of dependency pytest from 5.1.1 to 5.1.2
  Pipfile.lock
Labels: bot

#543 Automatic update of dependency jaeger-client from 4.0.0 to 4.1.0
  Pipfile.lock
Labels: bot
