Repository thoth-station/user-api, pull requests merged in 2019-07, with the labels that each got.

#477 Automatic update of dependency grpcio from 1.21.1 to 1.22.0
  Pipfile.lock
Labels: bot

#478 Automatic update of dependency grpcio-tools from 1.21.1 to 1.22.0
  Pipfile.lock
Labels: bot

#479 Automatic update of dependency prometheus-client from 0.7.0 to 0.7.1
  Pipfile.lock
Labels: bot

#480 Automatic update of dependency prometheus-flask-exporter from 0.8.1 to 0.9.0
  Pipfile.lock
Labels: bot

#481 Automatic update of dependency thoth-common from 0.8.11 to 0.9.1
  Pipfile.lock
Labels: bot

#482 Automatic update of dependency thoth-storages from 0.14.1 to 0.14.3
  Pipfile.lock
Labels: bot

#483 Automatic update of dependency pytest from 4.6.3 to 5.0.0
  Pipfile.lock
Labels: bot

#484 Automatic update of dependency flask from 1.0.3 to 1.0.4
  Pipfile.lock
Labels: bot

#485 Automatic update of dependency flask from 1.0.4 to 1.1.0
  Pipfile.lock
Labels: bot

#486 Automatic update of dependency opentracing-instrumentation from 3.0.1 to 3.1.1
  Pipfile.lock
Labels: bot

#487 Automatic update of dependency pytest from 5.0.0 to 5.0.1
  Pipfile.lock
Labels: bot

#488 Automatic update of dependency thoth-storages from 0.14.3 to 0.14.4
  Pipfile.lock
Labels: bot

#491 Automatic update of dependency flask from 1.1.0 to 1.1.1
  Pipfile.lock
Labels: bot

#492 Automatic update of dependency thoth-storages from 0.14.4 to 0.14.5
  Pipfile.lock
Labels: bot

#493 Automatic update of dependency thoth-storages from 0.14.5 to 0.14.6
  Pipfile.lock
Labels: bot

#495 Automatic update of dependency thoth-common from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot

#496 Automatic update of dependency thoth-storages from 0.14.6 to 0.14.7
  Pipfile.lock
Labels: bot

#489 python lint and minor deprecated syntax update
  pyproject.toml
  thoth/user_api/api_v1.py
Labels: approved, size/L

#498 Automatic update of dependency thoth-common from 0.9.2 to 0.9.3
  Pipfile.lock
Labels: bot

#499 Automatic update of dependency thoth-storages from 0.14.7 to 0.14.8
  Pipfile.lock
Labels: bot

#501 Explicitly state python type
  openapi/openapi.yaml
Labels: size/XS

#490 user-api support for build analysis and build log analysis
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
  thoth/user_api/configuration.py
Labels: approved, size/L

#502 Modified the names to standard convention
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#503 Removed thoth-build-analyzers dependencies from user-api
  Pipfile
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M

#504 Automatic update of dependency thoth-common from 0.9.3 to 0.9.5
  Pipfile.lock
Labels: bot

#505 Automatic update of dependency thoth-python from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot

#506 Automatic update of dependency thoth-storages from 0.14.8 to 0.16.0
  Pipfile.lock
Labels: bot

#507 Automatic update of dependency thoth-storages from 0.16.0 to 0.17.0
  Pipfile.lock
Labels: bot

#508 Automatic update of dependency thoth-storages from 0.17.0 to 0.18.0
  Pipfile.lock
Labels: bot
