Repository thoth-station/user-api, pull requests merged in 2019-11, with the labels that each got.

#636 Automatic update of dependency thoth-storages from 0.19.14 to 0.19.15
  Pipfile.lock
Labels: bot

#637 Automatic update of dependency grpcio from 1.24.3 to 1.25.0
  Pipfile.lock
Labels: bot

#638 Automatic update of dependency grpcio-tools from 1.24.3 to 1.25.0
  Pipfile.lock
Labels: bot

#639 Always parse runtime environment before submitting to adviser
  thoth/user_api/api_v1.py
Labels: approved, size/S

#640 Fix redirect to Swagger UI to make it work
  thoth/user_api/openapi_server.py
Labels: approved, size/XS

#641 Automatic update of dependency thoth-storages from 0.19.15 to 0.19.17
  Pipfile.lock
Labels: bot

#643 Automatic update of dependency thoth-storages from 0.19.17 to 0.19.18
  Pipfile.lock
Labels: bot

#644 Automatic update of dependency gunicorn from 19.9.0 to 20.0.0
  Pipfile.lock
Labels: bot

#646 Track only user endpoints
  thoth/user_api/openapi_server.py
Labels: approved, size/S, size/XS

#647 Automatic update of dependency thoth-storages from 0.19.18 to 0.19.19
  Pipfile.lock
Labels: bot

#648 Automatic update of dependency thoth-common from 0.9.14 to 0.9.15
  Pipfile.lock
Labels: bot

#649 Automatic update of dependency thoth-common from 0.9.15 to 0.9.16
  Pipfile.lock
Labels: bot, size/S

#650 Automatic update of dependency pytest from 5.2.2 to 5.2.3
  Pipfile.lock
Labels: bot, size/S

#652 Maintain one graph datababase adapter instance also in health checks
  thoth/user_api/api_v1.py
  thoth/user_api/openapi_server.py
Labels: approved, size/M

#654 Automatic update of dependency pytest from 5.2.3 to 5.2.4
  Pipfile.lock
Labels: bot, size/S

#657 Correct error response output
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#658 Correct output for error response for all queries
  thoth/user_api/api_v1.py
Labels: approved, size/S

#660 Automatic update of dependency thoth-storages from 0.19.19 to 0.19.22
  Pipfile.lock
Labels: bot, size/S

#659 New endpoints for Python packages in Thoth Knowledge Graph
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/L

#661 fixed /PythonPackagesCountInfoResponse_count_type
  openapi/openapi.yaml
Labels: approved, size/XS

#662 Add aiocontextvars for sentry-sdk integration with aiohttp
  Pipfile
  Pipfile.lock
Labels: approved, size/M

#664 Automatic update of dependency pytest from 5.2.4 to 5.3.0
  Pipfile.lock
Labels: bot, size/S

#663 Add sentry-sdk[flask] for Sentry Flask integration
  Pipfile
  Pipfile.lock
Labels: approved, size/S

#667 Automatic update of dependency thoth-storages from 0.19.22 to 0.19.23
  Pipfile.lock
Labels: bot, size/M

#668 updated some kinds, apiVersions
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/M

#669 Automatic update of dependency thoth-storages from 0.19.23 to 0.19.24
  Pipfile.lock
Labels: bot, size/S

#670 Automatic update of dependency gunicorn from 20.0.0 to 20.0.2
  Pipfile.lock
Labels: bot, size/S

#671 Automatic update of dependency sentry-sdk from 0.13.2 to 0.13.3
  Pipfile.lock
Labels: bot

#673 Automatic update of dependency gunicorn from 20.0.2 to 20.0.3
  Pipfile.lock
Labels: bot, size/M

#674 Automatic update of dependency sentry-sdk from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/M

#675 Automatic update of dependency pytest from 5.3.0 to 5.3.1
  Pipfile.lock
Labels: bot, size/XS

#676 Automatic update of dependency gunicorn from 20.0.3 to 20.0.4
  Pipfile.lock
Labels: bot, size/S

#678 Automatic update of dependency jaeger-client from 4.1.0 to 4.2.0
  Pipfile.lock
Labels: bot

#679 Automatic update of dependency thoth-common from 0.9.16 to 0.9.17
  Pipfile.lock
Labels: bot, size/L

#681 Automatic update of dependency thoth-analyzer from 0.1.4 to 0.1.5
  Pipfile.lock
Labels: bot, size/M

#684 Automatic update of dependency thoth-common from 0.9.17 to 0.9.19
  Pipfile.lock
Labels: bot, size/M

#683 Automatic update of dependency thoth-storages from 0.19.24 to 0.19.25
  Pipfile.lock
Labels: bot, size/XS
