Repository thoth-station/user-api, pull requests merged in 2019-04, with the labels that each got.

#414 Automatic update of dependency prometheus-flask-exporter from 0.7.0 to 0.7.1
  Pipfile.lock
Labels: bot

#415 Automatic update of dependency thoth-common from 0.8.1 to 0.8.2
  Pipfile.lock
Labels: bot

#417 Automatic update of dependency thoth-common from 0.8.2 to 0.8.3
  Pipfile.lock
Labels: bot

#418 Return Bad Request for invalid format request
  thoth/user_api/api_v1.py
  thoth/user_api/exceptions.py
  thoth/user_api/image.py
Labels: approved, size/S

#421 Automatic update of dependency thoth-common from 0.8.3 to 0.8.4
  Pipfile.lock
Labels: bot

#422 Introduce environment type parameter for image analysis
  thoth/user_api/api_v1.py
  thoth/user_api/swagger.yaml
Labels: approved, size/S

#419 Remove pylint zuul job
  .zuul.yaml
Labels: approved, size/XS

#423 Automatic update of dependency thoth-common from 0.8.4 to 0.8.5
  Pipfile.lock
Labels: bot

#424 Automatic update of dependency pytest from 4.4.0 to 4.4.1
  Pipfile.lock
Labels: bot

#425 Automatic update of dependency thoth-storages from 0.9.7 to 0.10.0
  Pipfile.lock
Labels: bot

#427 Automatic update of dependency prometheus-flask-exporter from 0.7.1 to 0.7.2
  Pipfile.lock
Labels: bot

#428 [WIP] dgraph requirements
  openshift/deployment-template.yaml
Labels: approved, size/M

#430 Automatic update of dependency thoth-storages from 0.10.0 to 0.11.0
  Pipfile.lock
Labels: bot

#426 Switch to Dgraph
  thoth/user_api/api_v1.py
  thoth/user_api/swagger.yaml
Labels: approved, size/XS

#429 Adjust deployment to respect new Dgraph configuration
  openshift/deployment-template.yaml
Labels: size/XS

#431 Fix env variable name of Dgraph instance in info endpoint
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#432 convert set to a list, so that it is json serializable
  thoth/user_api/api_v1.py
Labels: approved, size/XS
