Repository thoth-station/user-api, pull requests merged in 2019-09, with the labels that each got.

#544 Automatic update of dependency opentracing-instrumentation from 3.1.1 to 3.2.0
  Pipfile.lock
Labels: bot

#546 Switch from Dgraph to PostgreSQL in deployment
  openshift/deployment-template.yaml
Labels: approved, size/M

#548 Automatic update of dependency thoth-python from 0.6.1 to 0.6.2
  Pipfile.lock
Labels: bot

#549 Automatic update of dependency thoth-storages from 0.18.6 to 0.19.0
  Pipfile.lock
Labels: bot

#538 Start using Thoth's base image
  .s2i/bin/assemble
  openshift/buildConfig-template.yaml
Labels: approved, size/M

#550 Automatic update of dependency thoth-storages from 0.19.0 to 0.19.1
  Pipfile.lock
Labels: bot

#551 Automatic update of dependency thoth-storages from 0.19.1 to 0.19.2
  Pipfile.lock
Labels: bot

#552 Automatic update of dependency thoth-storages from 0.19.2 to 0.19.3
  Pipfile.lock
Labels: bot

#553 Automatic update of dependency thoth-storages from 0.19.3 to 0.19.4
  Pipfile.lock
Labels: bot

#554 Automatic update of dependency thoth-common from 0.9.8 to 0.9.9
  Pipfile.lock
Labels: bot

#555 Automatic update of dependency thoth-storages from 0.19.4 to 0.19.5
  Pipfile.lock
Labels: bot

#556 Automatic update of dependency thoth-common from 0.9.9 to 0.9.10
  Pipfile.lock
Labels: bot

#558 Automatic update of dependency thoth-analyzer from 0.1.2 to 0.1.3
  Pipfile.lock
Labels: bot

#559 Automatic update of dependency pytest from 5.1.2 to 5.1.3
  Pipfile.lock
Labels: bot

#561 Automatic update of dependency thoth-storages from 0.19.5 to 0.19.6
  Pipfile.lock
Labels: bot

#562 Automatic update of dependency thoth-python from 0.6.2 to 0.6.3
  Pipfile.lock
Labels: bot

#563 use postgresql hostname from thoth configmap
  openshift/deployment-template.yaml
Labels: approved, size/XS

#565 Automatic update of dependency thoth-storages from 0.19.6 to 0.19.7
  Pipfile.lock
Labels: bot

#567 updated cpu and memory allocation
  openshift/deployment-template.yaml
Labels: approved, size/XS

#568 Automatic update of dependency prometheus-flask-exporter from 0.9.1 to 0.10.0
  Pipfile.lock
Labels: bot

#569 Automatic update of dependency grpcio from 1.23.0 to 1.24.0
  Pipfile.lock
Labels: bot

#570 Automatic update of dependency grpcio-tools from 1.23.0 to 1.24.0
  Pipfile.lock
Labels: bot

#575 Automatic update of dependency thoth-analyzer from 0.1.3 to 0.1.4
  Pipfile.lock
Labels: bot

#576 Automatic update of dependency thoth-storages from 0.19.7 to 0.19.8
  Pipfile.lock
Labels: bot

#571 Remove unused function - log parsing has been moved to async handling
  thoth/user_api/api_v1.py
Labels: approved, size/S

#579 Add Thoth version information to each response
  thoth/user_api/openapi_server.py
Labels: approved, size/XS

#580 Automatic update of dependency pytest from 5.1.3 to 5.2.0
  Pipfile.lock
Labels: bot

#560 Check PostgreSQL in liveness or readiness probe
  thoth/user_api/openapi_server.py
Labels: approved, human_intervention_required, needs-rebase, size/XS

#581 Automatic update of dependency thoth-storages from 0.19.8 to 0.19.9
  Pipfile.lock
Labels: bot

#572 Be more safe when parsing webhook payload
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#577 Delete Info
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/S
