Repository thoth-station/user-api, pull requests merged in 2019-02, with the labels that each got.

#381 Skopeo flag for TLS verification has changed
  thoth/user_api/image.py
Labels: size/XS

#383 Update year in sources
  thoth/user_api/api_v1.py
  thoth/user_api/configuration.py
  thoth/user_api/entrypoint.py
  thoth/user_api/exceptions.py
  thoth/user_api/image.py
  thoth/user_api/parsing/__init__.py
  thoth/user_api/parsing/handlers/__init__.py
  thoth/user_api/parsing/handlers/base.py
  thoth/user_api/parsing/handlers/dnf.py
  thoth/user_api/parsing/handlers/pip.py
  thoth/user_api/parsing/handlers/pip3.py
  thoth/user_api/parsing/handlers/yum.py
Labels: size/M

#384 Use Python 3.6 by default
  Pipfile
Labels: size/XS

#385 Adjustments to respect Thoth configuration
  thoth/user_api/api_v1.py
  thoth/user_api/swagger.yaml
Labels: size/S

#386 Place runtime environment specification into a standalone model
  thoth/user_api/swagger.yaml
Labels: size/M

#387 Fix issues with Pipfile in s2i
  Pipfile
  Pipfile.lock
Labels: size/L

#389 Report unknown errors happening during image extraction
  thoth/user_api/image.py
Labels: size/XS

#390 Expose deployment specific configuration to users
  openshift/deployment-template.yaml
  thoth/user_api/api_v1.py
  thoth/user_api/swagger.yaml
Labels: size/M

#391 Introduce origin parameter
  thoth/user_api/api_v1.py
  thoth/user_api/swagger.yaml
Labels: size/M

#392 Automatic update of dependency prometheus-client from 0.5.0 to 0.6.0
  Pipfile.lock
Labels: bot

#393 Automatic update of dependency pytest from 4.2.1 to 4.3.0
  Pipfile.lock
Labels: bot

#395 Set WARNING level before the actual handler function
  thoth/user_api/entrypoint.py
Labels: size/XS
