Repository thoth-station/user-api, pull requests merged in 2019-10, with the labels that each got.

#583 fixing cors issue
  Pipfile
  Pipfile.lock
  thoth/user_api/openapi_server.py
Labels: approved, size/S, size/XS

#584 Automatic update of dependency attrs from 19.1.0 to 19.2.0
  Pipfile.lock
Labels: bot

#585 Automatic update of dependency thoth-common from 0.9.10 to 0.9.11
  Pipfile.lock
Labels: bot

#586 Automatic update of dependency opentracing-instrumentation from 3.2.0 to 3.2.1
  Pipfile.lock
Labels: bot

#587 Automatic update of dependency prometheus-flask-exporter from 0.10.0 to 0.11.0
  Pipfile.lock
Labels: bot

#588 Automatic update of dependency grpcio from 1.24.0 to 1.24.1
  Pipfile.lock
Labels: bot

#589 Automatic update of dependency grpcio-tools from 1.24.0 to 1.24.1
  Pipfile.lock
Labels: bot

#590 preparing 0.6.0-dev release
  openapi/openapi.yaml
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
  thoth/user_api/__init__.py
Labels: approved, size/M

#591 Automatic update of dependency pytest from 5.2.0 to 5.2.1
  Pipfile.lock
Labels: bot

#592 Automatic update of dependency thoth-common from 0.9.11 to 0.9.12
  Pipfile.lock
Labels: bot

#594 Automatic update of dependency thoth-python from 0.6.3 to 0.6.4
  Pipfile.lock
Labels: bot

#595 Automatic update of dependency thoth-common from 0.9.12 to 0.9.14
  Pipfile.lock
Labels: bot

#596 Automatic update of dependency attrs from 19.2.0 to 19.3.0
  Pipfile.lock
Labels: bot

#599 added a PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/S

#598 Feature: Get metadata for a Python package
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/L

#601 Report 404 if no metadata are found for the given package
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/S

#604 Fix component reference in openapi
  openapi/openapi.yaml
Labels: approved, do-not-merge/needs-rebase, size/XS

#605 Automatic update of dependency connexion from 2.3.0 to 2.4.0
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#606 Automatic update of dependency thoth-python from 0.6.4 to 0.6.5
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#607 Automatic update of dependency thoth-storages from 0.19.9 to 0.19.10
  Pipfile.lock
Labels: bot, do-not-merge/needs-rebase

#610 Automatic update of dependency grpcio from 1.24.1 to 1.24.3
  Pipfile.lock
Labels: bot

#611 Automatic update of dependency grpcio-tools from 1.24.1 to 1.24.3
  Pipfile.lock
Labels: bot

#612 Add missing properties to project metadata exposed
  openapi/openapi.yaml
Labels: approved, do-not-merge/needs-rebase, size/S

#608 Add software & hardware environment listing
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/L

#613 Remove Dgraph memories
  openapi/openapi.yaml
Labels: approved, size/M, size/XS

#614 Check if database schema is up2date in readiness probe
  thoth/user_api/entrypoint.py
Labels: approved, size/XS

#616 Fix entrypoint - remove old entrypoint
  thoth/user_api/entrypoint.py
  thoth/user_api/openapi_server.py
Labels: approved, size/L

#621 Automatic update of dependency pytest from 5.2.1 to 5.2.2
  Pipfile.lock
Labels: bot

#623 Fix issue when overwriting parameters
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#624 Automatic update of dependency thoth-storages from 0.19.10 to 0.19.11
  Pipfile.lock
Labels: bot

#625 Automatic update of dependency thoth-storages from 0.19.11 to 0.19.12
  Pipfile.lock
Labels: bot

#628 use github webhook variable html_url
  thoth/user_api/api_v1.py
Labels: approved, size/M

#627 Catch exception when database is not initialized
  thoth/user_api/openapi_server.py
Labels: approved, size/S, size/XS

#619 Do not introduce fatal fail if database schema was removed
  thoth/user_api/openapi_server.py
Labels: approved, size/XS

#631 Fix offset to start_offset
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#629 updated templates with annotations and param thoth-advise-value
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/M, size/S

#632 Update queries according to standardize naming convention
  thoth/user_api/api_v1.py
Labels: approved, size/S

#633 Automatic update of dependency thoth-storages from 0.19.12 to 0.19.13
  Pipfile.lock
Labels: bot

#634 Automatic update of dependency thoth-storages from 0.19.13 to 0.19.14
  Pipfile.lock
Labels: bot
