Repository thoth-station/user-api, pull requests merged in 2019-12, with the labels that each got.

#686 Automatic update of dependency prometheus-flask-exporter from 0.11.0 to 0.12.1
  Pipfile.lock
Labels: bot, size/L

#687 Automatic update of dependency thoth-common from 0.9.19 to 0.9.20
  Pipfile.lock
Labels: bot, size/XS

#677 Adjust endpoint and remove endpoint
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
  thoth/user_api/openapi_server.py
Labels: approved, size/M

#688 Automatic update of dependency thoth-common from 0.9.20 to 0.9.21
  Pipfile.lock
Labels: bot, size/M

#689 Automatic update of dependency thoth-analyzer from 0.1.5 to 0.1.6
  Pipfile.lock
Labels: bot, size/S

#690 Automatic update of dependency sentry-sdk from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/XS

#691 Automatic update of dependency thoth-storages from 0.19.25 to 0.19.26
  Pipfile.lock
Labels: bot, size/XS

#692 Automatic update of dependency thoth-storages from 0.19.26 to 0.19.27
  Pipfile.lock
Labels: bot, size/M

#693 Update Thoth configuration file and Thoth's s2i configuration
  .thoth.yaml
  .thothTemplate.yaml
  openshift/buildConfig-template.yaml
  thoth/user_api/openapi_server.py
Labels: approved, size/M

#694 Provide is_s2i flag on user API
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#695 Automatic update of dependency thoth-analyzer from 0.1.6 to 0.1.7
  Pipfile.lock
Labels: bot, size/S

#696 Automatic update of dependency thoth-common from 0.9.21 to 0.9.22
  Pipfile.lock
Labels: bot, size/M

#697 Automatic update of dependency pytest from 5.3.1 to 5.3.2
  Pipfile.lock
Labels: bot, size/S

#699 Automatic update of dependency connexion from 2.4.0 to 2.5.0
  Pipfile.lock
Labels: bot, size/S

#700 Automatic update of dependency thoth-storages from 0.19.27 to 0.19.30
  Pipfile.lock
Labels: bot, size/M

#701 Automatic update of dependency grpcio from 1.25.0 to 1.26.0
  Pipfile.lock
Labels: bot, size/L

#702 Automatic update of dependency grpcio-tools from 1.25.0 to 1.26.0
  Pipfile.lock
Labels: bot, size/L

#703 Automatic update of dependency connexion from 2.5.0 to 2.5.1
  Pipfile.lock
Labels: bot, size/S
