Repository thoth-station/user-api, pull requests merged in 2019-05, with the labels that each got.

#433 Automatic update of dependency thoth-storages from 0.11.0 to 0.11.1
  Pipfile.lock
Labels: bot

#434 Add library usage parameter to adviser's API
  thoth/user_api/api_v1.py
  thoth/user_api/swagger.yaml
Labels: approved, size/XS

#435 Implement User API using Stub API template
  Pipfile
  Pipfile.lock
  openapi/openapi.yaml
  openshift/deployment-template.yaml
  thoth/user_api/api_v1.py
  thoth/user_api/configuration.py
  thoth/user_api/openapi_server.py
  thoth/user_api/swagger.yaml
Labels: size/XXL

#437 Automatic update of dependency thoth-storages from 0.11.1 to 0.11.2
  Pipfile.lock
Labels: bot

#438 Automatic update of dependency pytest from 4.4.1 to 4.4.2
  Pipfile.lock
Labels: bot

#439 Consolidate endpoints for buildtime and runtime analyses
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: size/L

#441 Fix method names, provide image names only once
  thoth/user_api/api_v1.py
Labels: size/XS

#442 Automatic update of dependency thoth-storages from 0.11.2 to 0.11.3
  Pipfile.lock
Labels: bot

#443 Automatic update of dependency thoth-storages from 0.11.3 to 0.11.4
  Pipfile.lock
Labels: bot

#444 Automatic update of dependency pytest from 4.4.2 to 4.5.0
  Pipfile.lock
Labels: bot

#446 Automatic update of dependency thoth-common from 0.8.5 to 0.8.7
  Pipfile.lock
Labels: bot

#445 minor fix template for openshift >=3.11
  openshift/buildConfig-template.yaml
  openshift/imageStream-template.yaml
Labels: approved

#447 Automatic update of dependency requests from 2.21.0 to 2.22.0
  Pipfile.lock
Labels: bot

#449 Automatic update of dependency flask from 1.0.2 to 1.0.3
  Pipfile.lock
Labels: approved, bot

#450 Automatic update of dependency prometheus-flask-exporter from 0.7.2 to 0.7.3
  Pipfile.lock
Labels: bot

#448 Adjust functions for the endpoints related to environments
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved

#451 Automatic update of dependency prometheus-flask-exporter from 0.7.3 to 0.7.4
  Pipfile.lock
Labels: bot

#452 Automatic update of dependency prometheus-flask-exporter from 0.7.4 to 0.8.0
  Pipfile.lock
Labels: bot

#456 Automatic update of dependency grpcio from 1.20.1 to 1.21.1
  Pipfile.lock
Labels: bot

#457 Automatic update of dependency grpcio-tools from 1.20.1 to 1.21.1
  Pipfile.lock
Labels: bot

#454 Correct metric info
  openapi/openapi.yaml
  thoth/user_api/openapi_server.py
Labels: approved, needs-rebase, size/XS

#460 Migrate parsing API to thoth-build-analysers
  Pipfile
  thoth/user_api/api_v1.py
  thoth/user_api/parsing/__init__.py
  thoth/user_api/parsing/handlers/__init__.py
  thoth/user_api/parsing/handlers/base.py
  thoth/user_api/parsing/handlers/dnf.py
  thoth/user_api/parsing/handlers/pip.py
  thoth/user_api/parsing/handlers/pip3.py
  thoth/user_api/parsing/handlers/yum.py
Labels: size/XL

#459 Handle workload registered state
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#461 Update Pipfile.lock
  Pipfile.lock
Labels: approved, size/L

#462 Automatic update of dependency thoth-storages from 0.11.4 to 0.14.0
  Pipfile.lock
Labels: bot
