Repository thoth-station/user-api, pull requests merged in 2019-03, with the labels that each got.

#398 Increase memory requests in deployment
  openshift/deployment-template.yaml
Labels: size/XS

#399 Expose parameter for limiting number of latest versions
  thoth/user_api/api_v1.py
  thoth/user_api/swagger.yaml
Labels: size/XS

#401 remove unused stuff
  .zuul.yaml
Labels: approved, size/M

#402 reworked the service account part
  openshift/deployment-template.yaml
Labels: approved, size/M

#403 bouncing swagger api version to 0.4.0
  thoth/user_api/swagger.yaml
Labels: size/M

#404 Fix requirements so that updates are possible
  Pipfile
  Pipfile.lock
Labels: size/L

#406 Automatic update of dependency thoth-common from 0.7.1 to 0.8.1
  Pipfile.lock
Labels: bot

#408 Add Thoth's configuration file
  .thoth.yaml
Labels: size/S

#409 Automatic update of dependency thoth-python from 0.4.6 to 0.5.0
  Pipfile.lock
Labels: bot

#410 Automatic update of dependency thoth-storages from 0.9.6 to 0.9.7
  Pipfile.lock
Labels: bot

#411 Automatic update of dependency prometheus-flask-exporter from 0.6.0 to 0.7.0
  Pipfile.lock
Labels: bot

#412 Automatic update of dependency pytest from 4.3.1 to 4.4.0
  Pipfile.lock
Labels: bot
