Repository thoth-station/user-api, pull requests merged in 2020-09, with the labels that each got.

#1041 Automatic update of dependency prometheus-flask-exporter from 0.16.0 to 0.16.4
  Pipfile.lock
Labels: approved, bot, size/S

#1042 Automatic update of dependency thoth-common from 0.17.0 to 0.17.2
  Pipfile.lock
Labels: approved, bot, size/S

#1043 Automatic update of dependency sentry-sdk from 0.17.1 to 0.17.2
  Pipfile.lock
Labels: approved, bot, size/S

#1049 Automatic update of dependency thoth-common from 0.17.2 to 0.17.3
  Pipfile.lock
Labels: approved, bot, size/L

#1047 Automatic update of dependency sentry-sdk from 0.17.2 to 0.17.3
  Pipfile.lock
Labels: approved, bot, size/L

#1046 Automatic update of dependency prometheus-flask-exporter from 0.16.4 to 0.17.0
  Pipfile.lock
Labels: approved, bot, size/L

#1045 Automatic update of dependency attrs from 20.1.0 to 20.2.0
  Pipfile.lock
Labels: approved, bot, size/S

#1054 Release of version 0.6.16
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/S

#1055 Automatic update of dependency thoth-storages from 0.25.5 to 0.25.6
  Pipfile.lock
Labels: approved, bot, size/S

#1056 Automatic update of dependency sentry-sdk from 0.17.3 to 0.17.4
  Pipfile.lock
Labels: approved, bot, size/S

#1057 semantically correct name for qebhwt function
  Pipfile.lock
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/L

#1059 Correct exception type handled
  thoth/user_api/api_v1.py
Labels: size/XS

#1065 Automatic update of dependency thoth-common from 0.18.2 to 0.19.0
  Pipfile.lock
Labels: approved, bot, size/L

#1066 Automatic update of dependency thoth-storages from 0.25.7 to 0.25.9
  Pipfile.lock
Labels: approved, bot, size/L

#1062 Automatic update of dependency pytest from 6.0.1 to 6.0.2
  Pipfile.lock
Labels: approved, bot, size/XS

#1067 Automatic update of dependency sentry-sdk from 0.17.4 to 0.17.6
  Pipfile.lock
Labels: approved, bot, size/XS

#1069 Automatic update of dependency sentry-sdk from 0.17.4 to 0.17.6
  Pipfile.lock
Labels: approved, bot, size/S

#1068 Release of version 0.6.17
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot

#1071 Automatic update of dependency prometheus-flask-exporter from 0.17.0 to 0.18.0
  Pipfile.lock
Labels: approved, bot, size/L

#1072 Automatic update of dependency thoth-common from 0.19.0 to 0.20.0
  Pipfile.lock
Labels: approved, bot, size/L

#1073 Automatic update of dependency thoth-storages from 0.25.9 to 0.25.11
  Pipfile.lock
Labels: approved, bot, size/L

#1076 Automatic update of dependency thoth-python from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: approved, bot, size/XS

#1074 Automatic update of dependency sentry-sdk from 0.17.6 to 0.17.8
  Pipfile.lock
Labels: approved, bot, size/XS

#1083 Release of version 0.6.18
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/S

#1063 Feature/user api message prod
  Pipfile
  Pipfile.lock
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
  thoth/user_api/configuration.py
  thoth/user_api/openapi_server.py
Labels: approved, do-not-merge/needs-rebase, size/L

#1084 Automatic update of dependency thoth-messaging from 0.7.2 to 0.7.6
  Pipfile.lock
Labels: approved, bot, size/M

#1086 Automatic update of dependency pytest from 6.0.2 to 6.1.0
  Pipfile.lock
Labels: approved, bot, size/M

#1087 Catch missing exception
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#1089 Automatic update of dependency thoth-storages from 0.25.11 to 0.25.13
  Pipfile.lock
Labels: approved, bot, size/S

#1090 Automatic update of dependency thoth-messaging from 0.7.6 to 0.7.8
  Pipfile.lock
Labels: approved, bot, size/S

#1091 Release of version 0.6.19
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/S
