Repository thoth-station/user-api, pull requests merged in 2020-04, with the labels that each got.

#830 Automatic update of dependency thoth-common from 0.12.1 to 0.12.5
  Pipfile.lock
Labels: bot, size/M

#831 Automatic update of dependency thoth-storages from 0.22.5 to 0.22.7
  Pipfile.lock
Labels: bot, size/XS

#833 Automatic update of dependency thoth-common from 0.12.5 to 0.12.6
  Pipfile.lock
Labels: bot, size/XS

#834 Automatic update of dependency grpcio from 1.27.2 to 1.28.0
  Pipfile.lock
Labels: bot, size/M

#835 Automatic update of dependency grpcio-tools from 1.27.2 to 1.28.0
  Pipfile.lock
Labels: bot, size/M

#836 Missing exception import
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#837 Remove variable not required
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#839 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/L

#840 Make GitHub events parameters and debug options to the cache
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#843 Automatic update of dependency grpcio from 1.27.2 to 1.28.1
  Pipfile.lock
Labels: bot, size/M

#844 Automatic update of dependency grpcio-tools from 1.27.2 to 1.28.1
  Pipfile.lock
Labels: bot, size/M

#845 Increase memory requirements for the s2i build
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#846 Increase resources for build even more
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#848 Automatic update of dependency thoth-common from 0.12.6 to 0.12.7
  Pipfile.lock
Labels: bot, size/L

#849 Remove latest version restriction from .thoth.yaml
  .thoth.yaml
Labels: approved, size/XS

#851 Automatic update of dependency thoth-common from 0.12.7 to 0.12.8
  Pipfile.lock
Labels: bot, size/S

#852 Automatic update of dependency thoth-common from 0.12.8 to 0.12.9
  Pipfile.lock
Labels: bot, size/S

#841 Distinguish debug option when accessing the cache for provenance results
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#828 Configure logging for access log
  .coafile
  gunicorn.conf.py
  openshift/deployment-template.yaml
Labels: approved, size/XS

#847 Pin grpcio to <1.28
  Pipfile
  Pipfile.lock
  openshift/buildConfig-template.yaml
Labels: approved, human_intervention_required, size/L, thoth/human_intervention_required

#853 Add filters for python packages count
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M

#855 Automatic update of dependency thoth-python from 0.9.1 to 0.9.2
  Pipfile.lock
Labels: bot, size/L

#857 Automatic update of dependency thoth-common from 0.12.9 to 0.12.10
  Pipfile.lock
Labels: bot, size/S

#856 Add platform information to OpenAPI spec
  openapi/openapi.yaml
Labels: approved, size/XS

#859 Added a route to receive webhook
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M

#860 Automatic update of dependency thoth-common from 0.12.10 to 0.13.0
  Pipfile.lock
Labels: bot, size/M

#861 Automatic update of dependency connexion from 2.6.0 to 2.7.0
  Pipfile.lock
Labels: bot, size/XS

#862 Automatic update of dependency thoth-storages from 0.22.7 to 0.22.8
  Pipfile.lock
Labels: bot, size/XS

#864 condition for argo check before workflow status check
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#866 Automatic update of dependency thoth-common from 0.13.0 to 0.13.1
  Pipfile.lock
Labels: bot, size/S

#868 Use correct keys
  openapi/openapi.yaml
Labels: approved, size/S

#869 Automatic update of dependency thoth-storages from 0.22.8 to 0.22.9
  Pipfile.lock
Labels: bot, size/S

#865 Handle Github Webhooks
  thoth/user_api/api_v1.py
Labels: approved, size/S

#872 fix key error state
  thoth/user_api/api_v1.py
Labels: approved, size/S, size/XS

#873 Automatic update of dependency thoth-common from 0.13.1 to 0.13.2
  Pipfile.lock
Labels: bot, size/S
