Repository thoth-station/user-api, pull requests merged in 2020-01, with the labels that each got.

#704 Automatic update of dependency thoth-storages from 0.19.30 to 0.20.0
  Pipfile.lock
Labels: bot, size/L

#705 Automatic update of dependency thoth-storages from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: bot, size/S

#707 Automatic update of dependency thoth-storages from 0.20.1 to 0.20.2
  Pipfile.lock
Labels: bot, size/XS

#708 Automatic update of dependency thoth-storages from 0.20.2 to 0.20.3
  Pipfile.lock
Labels: bot, size/S

#709 Automatic update of dependency thoth-storages from 0.20.3 to 0.20.4
  Pipfile.lock
Labels: bot, size/XS

#710 Automatic update of dependency thoth-python from 0.7.1 to 0.8.0
  Pipfile.lock
Labels: bot, size/M

#711 Automatic update of dependency thoth-storages from 0.20.4 to 0.20.5
  Pipfile.lock
Labels: bot, size/XS

#712 Automatic update of dependency thoth-common from 0.9.22 to 0.9.23
  Pipfile.lock
Labels: bot, size/XS

#713 Do not run adviser from bc in debug mode
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#714 Automatic update of dependency thoth-storages from 0.20.5 to 0.20.6
  Pipfile.lock
Labels: bot, size/S

#715 Automatic update of dependency sentry-sdk from 0.13.5 to 0.14.0
  Pipfile.lock
Labels: bot, size/XS

#716 Automatic update of dependency thoth-python from 0.8.0 to 0.9.0
  Pipfile.lock
Labels: bot, size/XS

#717 Automatic update of dependency thoth-python from 0.9.0 to 0.9.1
  Pipfile.lock
Labels: bot, size/S

#718 Automatic update of dependency thoth-storages from 0.20.6 to 0.21.0
  Pipfile.lock
Labels: bot, size/M

#719 Automatic update of dependency thoth-common from 0.9.23 to 0.9.24
  Pipfile.lock
Labels: bot, size/XS

#720 Automatic update of dependency thoth-storages from 0.21.0 to 0.21.1
  Pipfile.lock
Labels: bot, size/XS

#721 Automatic update of dependency thoth-storages from 0.21.1 to 0.21.2
  Pipfile.lock
Labels: bot, size/XS

#722 Automatic update of dependency thoth-storages from 0.21.2 to 0.21.3
  Pipfile.lock
Labels: bot, size/XS

#706 Happy new year!
  thoth/user_api/api_v1.py
  thoth/user_api/configuration.py
  thoth/user_api/exceptions.py
  thoth/user_api/image.py
  thoth/user_api/openapi_server.py
Labels: approved, size/S

#723 Automatic update of dependency thoth-storages from 0.21.3 to 0.21.4
  Pipfile.lock
Labels: bot, size/M

#724 Automatic update of dependency thoth-storages from 0.21.4 to 0.21.5
  Pipfile.lock
Labels: bot, size/S

#725 Automatic update of dependency thoth-common from 0.9.24 to 0.9.25
  Pipfile.lock
Labels: bot, size/XS

#726 use build-report instead of build-analyze
  thoth/user_api/api_v1.py
Labels: approved, size/S

#727 Automatic update of dependency thoth-storages from 0.21.5 to 0.21.6
  Pipfile.lock
Labels: bot, size/S

#728 Automatic update of dependency thoth-common from 0.9.25 to 0.9.26
  Pipfile.lock
Labels: bot, size/S

#729 Automatic update of dependency jaeger-client from 4.2.0 to 4.3.0
  Pipfile.lock
Labels: bot, size/S

#730 Automatic update of dependency thoth-storages from 0.21.6 to 0.21.7
  Pipfile.lock
Labels: bot, size/M

#731 Automatic update of dependency thoth-analyzer from 0.1.7 to 0.1.8
  Pipfile.lock
Labels: bot, size/S

#732 Automatic update of dependency thoth-common from 0.9.26 to 0.9.27
  Pipfile.lock
Labels: bot, size/XS

#733 Automatic update of dependency thoth-common from 0.9.27 to 0.9.28
  Pipfile.lock
Labels: bot, size/XS

#734 Automatic update of dependency pytest from 5.3.2 to 5.3.3
  Pipfile.lock
Labels: bot, size/M

#736 Added nullables to Runtime Environment properties
  openapi/openapi.yaml
Labels: approved, size/XS

#741 Automatic update of dependency thoth-common from 0.9.28 to 0.9.29
  Pipfile.lock
Labels: bot, size/M

#742 Automatic update of dependency thoth-storages from 0.21.7 to 0.21.8
  Pipfile.lock
Labels: bot, size/S

#743 Automatic update of dependency pytest from 5.3.3 to 5.3.4
  Pipfile.lock
Labels: bot, size/S

#744 Automatic update of dependency thoth-storages from 0.21.8 to 0.21.9
  Pipfile.lock
Labels: bot, size/S

#745 Automatic update of dependency thoth-storages from 0.21.9 to 0.21.10
  Pipfile.lock
Labels: bot, size/S

#746 Automatic update of dependency sentry-sdk from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: bot, size/M

#748 New Endpoint to schedule Thamos Advise workflow for QebHwt
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M

#749 Add temporary variable to use Argo workflow
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#753 Correct wrong datatype
  openapi/openapi.yaml
Labels: approved, size/XS

#754 Automatic update of dependency thoth-common from 0.9.29 to 0.9.30
  Pipfile.lock
Labels: bot, size/M

#755 Automatic update of dependency thoth-common from 0.9.30 to 0.9.31
  Pipfile.lock
Labels: bot, size/XS

#756 Automatic update of dependency thoth-storages from 0.21.10 to 0.21.11
  Pipfile.lock
Labels: bot, size/XS

#757 Added an extra exception catch
  thoth/user_api/api_v1.py
  thoth/user_api/exceptions.py
  thoth/user_api/image.py
Labels: approved, size/S

#759 Standardize parameters for GitHubApp workflow scheduling
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/S

#758 Add GitHub specific metadata for GitHub integration
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M

#760 Automatic update of dependency thoth-common from 0.9.31 to 0.10.0
  Pipfile.lock
Labels: bot, size/M

#761 Add endpoint exposing package dependencies
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/L

#762 Automatic update of dependency pytest from 5.3.4 to 5.3.5
  Pipfile.lock
Labels: bot, size/M

#763 Automatic update of dependency connexion from 2.5.1 to 2.6.0
  Pipfile.lock
Labels: bot, size/XS

#764 Add missing import
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#765 POST endpoint accepts input body
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#766 Use string for env variable
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/S

#768 Automatic update of dependency thoth-common from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: bot, size/S

#767 Introduce env var for Thoth host to be used in GitHub App
  openshift/deployment-template.yaml
  thoth/user_api/api_v1.py
  thoth/user_api/configuration.py
Labels: approved, size/XS
