Repository thoth-station/user-api, pull requests merged in 2020-08, with the labels that each got.

#997 Automatic update of dependency attrs from 19.3.0 to 20.1.0
  Pipfile.lock
Labels: approved, bot, size/L

#998 Automatic update of dependency thoth-common from 0.16.0 to 0.16.1
  Pipfile.lock
Labels: approved, bot, size/L

#999 Automatic update of dependency thoth-python from 0.10.0 to 0.10.1
  Pipfile.lock
Labels: approved, bot, size/L

#1000 Automatic update of dependency thoth-storages from 0.25.0 to 0.25.3
  Pipfile.lock
Labels: approved, bot, size/L

#1001 Automatic update of dependency sentry-sdk from 0.16.2 to 0.16.5
  Pipfile.lock
Labels: approved, bot, size/L

#1008 Automatic update of dependency sentry-sdk from 0.16.5 to 0.17.0
  Pipfile.lock
Labels: approved, bot, size/M

#1009 Fix unhandled workflow state in responses
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#1010 Fix variable reference
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#1013 Release of version 0.6.11
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/XS

#907 Add endpoint for listing supported platforms
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: size/S

#1015 Turn on smart changelog to group messages using AI/ML
  .thoth.yaml
Labels: size/XS

#1017 Release of version 0.6.12
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/XS

#1021 Automatic update of dependency thoth-common from 0.16.1 to 0.17.0
  Pipfile.lock
Labels: approved, bot, size/M

#1019 Fix obtaining logs when Argo workflows are used
  thoth/user_api/api_v1.py
Labels: approved, size/M

#1024 Fix mypy complains about typing
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#1025 Release of version 0.6.13
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/S

#1027 Relock dependencies due to Pipenv/Kebechet bug
  Pipfile.lock
Labels: size/M

#1033 Automatic update of dependency flask-cors from 3.0.8 to 3.0.9
  Pipfile.lock
Labels: approved, bot, size/M

#1034 Include service version in response headers
  thoth/user_api/openapi_server.py
Labels: approved, size/XS

#1030 Release of version 0.6.14
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, kind/bug, size/S

#1039 Release of version 0.6.15
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/S
