Repository thoth-station/user-api, pull requests merged in 2020-02, with the labels that each got.

#770 Automatic update of dependency thoth-common from 0.10.1 to 0.10.2
  Pipfile.lock
Labels: bot, size/XS

#769 Moved common parameters to components
  openapi/openapi.yaml
Labels: approved, size/L

#771 Automatic update of dependency grpcio from 1.26.0 to 1.27.0
  Pipfile.lock
Labels: bot, size/L

#772 Automatic update of dependency grpcio-tools from 1.26.0 to 1.27.0
  Pipfile.lock
Labels: bot, size/M

#773 Modify parameters for GitHub App
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/S

#776 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/L

#777 Automatic update of dependency thoth-common from 0.10.2 to 0.10.3
  Pipfile.lock
Labels: bot, size/XS

#778 Automatic update of dependency thoth-common from 0.10.3 to 0.10.4
  Pipfile.lock
Labels: bot, size/XS

#779 Automatic update of dependency thoth-common from 0.10.4 to 0.10.5
  Pipfile.lock
Labels: bot, size/M

#780 Automatic update of dependency grpcio from 1.26.0 to 1.27.1
  Pipfile.lock
Labels: bot, size/L

#781 Automatic update of dependency grpcio-tools from 1.26.0 to 1.27.1
  Pipfile.lock
Labels: bot, size/L

#782 Automatic update of dependency prometheus-flask-exporter from 0.12.1 to 0.12.2
  Pipfile.lock
Labels: bot, size/XS

#784 Automatic update of dependency thoth-storages from 0.21.11 to 0.22.0
  Pipfile.lock
Labels: bot, size/S

#783 Update .thoth.yaml
  .thoth.yaml
Labels: approved, size/S

#785 Automatic update of dependency thoth-storages from 0.22.0 to 0.22.1
  Pipfile.lock
Labels: bot, size/S

#786 Automatic update of dependency thoth-common from 0.10.5 to 0.10.6
  Pipfile.lock
Labels: bot, size/XS

#787 Automatic update of dependency thoth-storages from 0.22.1 to 0.22.2
  Pipfile.lock
Labels: bot, size/S

#788 Automatic update of dependency grpcio from 1.27.1 to 1.27.2
  Pipfile.lock
Labels: bot, size/L

#789 Automatic update of dependency grpcio-tools from 1.27.1 to 1.27.2
  Pipfile.lock
Labels: bot, size/M

#790 Automatic update of dependency thoth-common from 0.10.6 to 0.10.7
  Pipfile.lock
Labels: bot, size/XS

#793 Automatic update of dependency requests from 2.22.0 to 2.23.0
  Pipfile.lock
Labels: bot, size/M

#795 Correct datatype
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#798 Automatic update of dependency thoth-common from 0.10.7 to 0.10.8
  Pipfile.lock
Labels: bot, size/M

#800 Advise route fix
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#801 Automatic update of dependency thoth-storages from 0.22.2 to 0.22.3
  Pipfile.lock
Labels: bot, size/M

#803 Automatic update of dependency sentry-sdk from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: bot, size/XS

#804 Automatic update of dependency thoth-common from 0.10.8 to 0.10.9
  Pipfile.lock
Labels: bot, size/S
