Repository thoth-station/user-api, pull requests merged in 2020-07, with the labels that each got.

#949 Fixed pre-commit errors
  .pre-commit-config.yaml
  thoth/user_api/api_v1.py
  thoth/user_api/payload_filter.py
Labels: approved, size/S

#944 Drop result-api bits
  thoth/user_api/api_v1.py
  thoth/user_api/configuration.py
Labels: approved, size/S

#947 Remove OpenShift related files as they are part of thoth-application
  openshift/buildConfig-template.yaml
  openshift/deployment-template.yaml
  openshift/imageStream-template.yaml
Labels: approved, size/L

#948 Automatic update of dependency thoth-common from 0.13.13 to 0.14.0
  Pipfile.lock
Labels: approved, bot, size/L

#952 Release of version 0.6.6
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/S

#958 Automatic update of dependency sentry-sdk from 0.15.1 to 0.16.1
  Pipfile.lock
Labels: approved, bot, size/M

#957 Automatic update of dependency thoth-storages from 0.24.0 to 0.24.3
  Pipfile.lock
Labels: approved, bot, size/M

#956 Automatic update of dependency thoth-common from 0.14.0 to 0.14.1
  Pipfile.lock
Labels: approved, bot, size/M

#955 Automatic update of dependency prometheus-flask-exporter from 0.14.1 to 0.15.0
  Pipfile.lock
Labels: approved, bot, size/M

#960 Release of version 0.6.7
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/XS

#963 Release of version 0.6.8
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/XL

#964 Removed un-necessary variable
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#966 Automatic update of dependency thoth-common from 0.14.1 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/S

#967 Remove latest versions limitation
  .thothTemplate.yaml
Labels: approved, size/XS

#968 Remove limit_latest_versions from API
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#969 Automatic update of dependency thoth-storages from 0.24.3 to 0.24.4
  Pipfile.lock
Labels: approved, bot, size/XS

#973 Automatic update of dependency prometheus-flask-exporter from 0.15.0 to 0.15.4
  Pipfile.lock
Labels: approved, bot, size/M

#974 Automatic update of dependency thoth-common from 0.14.2 to 0.15.0
  Pipfile.lock
Labels: approved, bot, size/M

#975 Automatic update of dependency thoth-storages from 0.24.4 to 0.24.5
  Pipfile.lock
Labels: approved, bot, size/M

#976 Automatic update of dependency sentry-sdk from 0.16.1 to 0.16.2
  Pipfile.lock
Labels: approved, bot, size/M

#977 Automatic update of dependency thoth-storages from 0.24.4 to 0.24.5
  Pipfile.lock
Labels: approved, bot, size/S

#979 Automatic update of dependency pytest from 5.4.3 to 6.0.0
  Pipfile.lock
Labels: approved, bot, size/XS

#971 Changed to new workflow status
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/L

#970 Extend recommendation types
  openapi/openapi.yaml
Labels: approved, kind/feature, size/XS

#980 Moving changed function
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#981 Source type is nullable
  openapi/openapi.yaml
Labels: approved, size/XS

#987 Fix
  thoth/user_api/payload_filter.py
Labels: approved, size/XS

#989 Release of version 0.6.9
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/S

#991 Wrong exception caught
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#993 Automatic update of dependency thoth-storages from 0.24.5 to 0.25.0
  Pipfile.lock
Labels: approved, bot, size/M

#994 Automatic update of dependency pytest from 6.0.0 to 6.0.1
  Pipfile.lock
Labels: approved, bot, size/M

#992 Automatic update of dependency thoth-common from 0.15.0 to 0.16.0
  Pipfile.lock
Labels: approved, bot, size/XS
