Repository thoth-station/user-api, pull requests merged in 2020-10, with the labels that each got.

#1093 Automatic update of dependency thoth-storages from 0.25.13 to 0.25.15
  Pipfile.lock
Labels: approved, bot, size/M

#1094 Automatic update of dependency sentry-sdk from 0.17.8 to 0.18.0
  Pipfile.lock
Labels: approved, bot, size/M

#1095 Automatic update of dependency thoth-messaging from 0.7.8 to 0.7.10
  Pipfile.lock
Labels: approved, bot, size/M

#1096 Automatic update of dependency pytest from 6.1.0 to 6.1.1
  Pipfile.lock
Labels: approved, bot, size/M

#1100 Automatic update of dependency thoth-common from 0.20.0 to 0.20.1
  Pipfile.lock
Labels: approved, bot, size/M

#1102 Release of version 0.6.20
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/S

#1101 Automatic update of dependency thoth-messaging from 0.7.10 to 0.7.11
  Pipfile.lock
Labels: approved, bot, size/XS

#1104 Expose all packages
  thoth/user_api/openapi_server.py
Labels: approved, size/XS

#1105 Automatic update of dependency prometheus-flask-exporter from 0.18.0 to 0.18.1
  Pipfile.lock
Labels: approved, bot, size/L

#1106 Automatic update of dependency thoth-common from 0.20.1 to 0.20.2
  Pipfile.lock
Labels: approved, bot, size/L

#1108 Automatic update of dependency thoth-messaging from 0.7.11 to 0.7.13
  Pipfile.lock
Labels: approved, bot, size/XS

#1107 Automatic update of dependency sentry-sdk from 0.18.0 to 0.19.1
  Pipfile.lock
Labels: approved, bot, size/L

#1111 Automatic update of dependency thoth-messaging from 0.7.13 to 0.8.2
  Pipfile.lock
Labels: approved, bot, size/XS

#1113 Automatic update of dependency pytest from 6.1.1 to 6.1.2
  Pipfile.lock
Labels: approved, bot, size/S

#1114 Automatic update of dependency thoth-common from 0.20.2 to 0.20.4
  Pipfile.lock
Labels: approved, bot, size/XS
