Repository thoth-station/user-api, pull requests merged in 2020-11, with the labels that each got.

#1116 Automatic update of dependency thoth-storages from 0.25.15 to 0.25.16
  Pipfile.lock
Labels: approved, bot, size/M

#1117 Automatic update of dependency sentry-sdk from 0.19.1 to 0.19.2
  Pipfile.lock
Labels: approved, bot, size/M

#1119 Place metadata info into Python packages section
  openapi/openapi.yaml
Labels: approved, size/XS

#1120 Place dependencies under package to conform other endpoints
  openapi/openapi.yaml
Labels: approved, size/XS

#1126 Automatic update of dependency thoth-storages from 0.25.16 to 0.25.17
  Pipfile.lock
Labels: approved, bot, size/S

#1128 Automatic update of dependency attrs from 20.2.0 to 20.3.0
  Pipfile.lock
Labels: approved, bot, size/S

#1129 Automatic update of dependency thoth-storages from 0.25.17 to 0.26.0
  Pipfile.lock
Labels: approved, bot, size/S

#1124 Fix 404 for queued requests
  thoth/user_api/api_v1.py
Labels: approved, size/M

#1131 Release of version 0.7.0
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/S

#1134 Make sure the advise endpoint is available when becoming ready
  thoth/user_api/openapi_server.py
Labels: approved, size/S

#1136 Messaging 0.7.13
  Pipfile
  Pipfile.lock
  thoth/user_api/api_v1.py
Labels: approved, size/L

#1121 Provide an endpoint for listing available Python package versions
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
  thoth/user_api/openapi_server.py
Labels: approved, size/M

#1138 Release of version 0.8.0
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/XS

#1140 Automatic update of dependency requests from 2.24.0 to 2.25.0
  Pipfile.lock
Labels: approved, bot, size/L

#1141 Automatic update of dependency thoth-storages from 0.26.0 to 0.26.1
  Pipfile.lock
Labels: approved, bot, size/L

#1143 Removed list endpoints
  openapi/openapi.yaml
Labels: approved, size/M

#1145 Automatic update of dependency prometheus-client from 0.8.0 to 0.9.0
  Pipfile.lock
Labels: approved, bot, size/L

#1147 Automatic update of dependency sentry-sdk from 0.19.2 to 0.19.3
  Pipfile.lock
Labels: approved, bot, size/L

#1146 Automatic update of dependency thoth-storages from 0.26.1 to 0.27.0
  Pipfile.lock
Labels: approved, bot, size/XS

#1151 Release of version 0.9.0
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot, size/S

#1144 get workflow node status
  thoth/user_api/api_v1.py
Labels: approved, size/S
