Repository thoth-station/user-api, pull requests merged in 2020-03, with the labels that each got.

#806 Image pull policy
  openshift/deployment-template.yaml
  thoth/user_api/image.py
Labels: approved

#807 Remove check on graph initialization
  thoth/user_api/openapi_server.py
Labels: approved

#808 Automatic update of dependency prometheus-flask-exporter from 0.12.2 to 0.13.0
  Pipfile.lock
Labels: bot, size/M

#809 Automatic update of dependency thoth-common from 0.10.9 to 0.10.11
  Pipfile.lock
Labels: bot, size/XS

#812 Automatic update of dependency pytest from 5.3.5 to 5.4.0
  Pipfile.lock
Labels: bot, size/S

#802 Fallback if thoth fails to give advise in bc
  openshift/buildConfig-template.yaml
Labels: approved, size/XS

#813 Automatic update of dependency pytest from 5.4.0 to 5.4.1
  Pipfile.lock
Labels: bot, size/S

#811 Get status of an adviser run from a Workflow
  thoth/user_api/api_v1.py
Labels: size/M

#816 Fix for GraphDatabase has no attribute get_python_package_index_urls
  thoth/user_api/api_v1.py
Labels: approved

#815 Issue check on not found (404) only
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#817 Add env variable to use Argo
  openshift/deployment-template.yaml
Labels: approved

#819 Automatic update of dependency thoth-common from 0.10.11 to 0.10.12
  Pipfile.lock
Labels: bot

#822 Automatic update of dependency sentry-sdk from 0.14.2 to 0.14.3
  Pipfile.lock
Labels: bot, size/S

#823 Automatic update of dependency thoth-common from 0.10.12 to 0.12.0
  Pipfile.lock
Labels: bot, size/XS

#824 introduced a service version string
  .gitignore
  thoth/user_api/openapi_server.py
Labels: approved, enhancement, size/S

#825 Automatic update of dependency thoth-common from 0.12.0 to 0.12.1
  Pipfile.lock
Labels: bot, size/S

#829 Introduce adviser's dev flag to consider or not consider dev deps
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved

#821 Automatic update of dependency thoth-storages from 0.22.3 to 0.22.5
  Pipfile.lock
Labels: bot, size/XS
