Repository thoth-station/user-api, pull requests merged in 2020-05, with the labels that each got.

#875 Automatic dependency re-locking
  Pipfile.lock
Labels: bot, size/S

#876 Automatic update of dependency pytest from 5.4.1 to 5.4.2
  Pipfile.lock
Labels: bot, size/M

#878 Release of version 0.6.1
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: bot, size/XL

#881 Automatic update of dependency thoth-storages from 0.22.9 to 0.22.10
  Pipfile.lock
Labels: bot, size/M

#882 Automatic update of dependency sentry-sdk from 0.14.3 to 0.14.4
  Pipfile.lock
Labels: bot, size/M

#883 Introduce source_type flag
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: size/M

#870 Remove unused environment variable
  openshift/buildConfig-template.yaml
Labels: size/XS

#884 Remove logic
  thoth/user_api/api_v1.py
Labels: approved, size/S

#885 Automatic update of dependency thoth-common from 0.13.3 to 0.13.4
  Pipfile.lock
Labels: bot, size/L

#886 Make integration enum lower-case on endpoints
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/S

#887 Automatic update of dependency thoth-storages from 0.22.10 to 0.22.11
  Pipfile.lock
Labels: bot, size/M

#888 Automatic update of dependency thoth-common from 0.13.4 to 0.13.5
  Pipfile.lock
Labels: bot, size/XS

#889 Automatic update of dependency thoth-common from 0.13.5 to 0.13.6
  Pipfile.lock
Labels: bot, size/XS

#891 Automatic update of dependency prometheus-client from 0.7.1 to 0.8.0
  Pipfile.lock
Labels: bot, size/S

#892 Automatic update of dependency thoth-common from 0.13.6 to 0.13.7
  Pipfile.lock
Labels: bot, size/S

#890 Added filter methods and installation methods
  thoth/user_api/api_v1.py
  thoth/user_api/payload_filter.py
Labels: approved, size/L

#894 Automatic update of dependency thoth-storages from 0.22.11 to 0.22.12
  Pipfile.lock
Labels: bot, size/M

#895 Automatic update of dependency thoth-common from 0.13.7 to 0.13.8
  Pipfile.lock
Labels: bot, size/XS
