Repository thoth-station/user-api, pull requests merged in 2020-06, with the labels that each got.

#896 Filter out deprecated event's
  thoth/user_api/payload_filter.py
Labels: approved, size/XS

#898 Automatic update of dependency pytest from 5.4.2 to 5.4.3
  Pipfile.lock
Labels: bot, size/S

#900 Be more specific with method signatures
  thoth/user_api/payload_filter.py
Labels: approved, size/S

#899 Ignore kebechet run on push event on bot branch
  thoth/user_api/payload_filter.py
Labels: approved, size/XS

#901 Use frozenset for constants
  thoth/user_api/payload_filter.py
Labels: approved, size/XS

#903 Release of version 0.6.2
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: bot, size/S

#904 Also listen to installation events
  thoth/user_api/payload_filter.py
Labels: approved, size/S

#905 Lower letters
  openapi/openapi.yaml
Labels: approved, size/S

#909 Fix serialization issues
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#911 Automatic update of dependency thoth-common from 0.13.8 to 0.13.9
  Pipfile.lock
Labels: bot, size/M

#916 Automatic update of dependency thoth-common from 0.13.10 to 0.13.11
  Pipfile.lock
Labels: bot, size/M

#917 Automatic update of dependency thoth-storages from 0.22.12 to 0.23.0
  Pipfile.lock
Labels: bot, size/XS

#920 Automatic update of dependency prometheus-flask-exporter from 0.13.0 to 0.14.1
  Pipfile.lock
Labels: approved, bot

#922 Automatic update of dependency thoth-common from 0.13.11 to 0.13.12
  Pipfile.lock
Labels: approved, bot

#921 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: approved, bot

#923 Automatic update of dependency thoth-python from 0.9.2 to 0.10.0
  Pipfile.lock
Labels: approved, bot

#926 Automatic update of dependency requests from 2.23.0 to 2.24.0
  Pipfile.lock
Labels: approved, bot

#925 Automatic update of dependency sentry-sdk from 0.14.4 to 0.15.1
  Pipfile.lock
Labels: approved, bot

#924 Automatic update of dependency thoth-storages from 0.23.0 to 0.23.2
  Pipfile.lock
Labels: approved, bot

#928 update github project templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
Labels: approved

#930 Automatic update of dependency opentracing-instrumentation from 3.2.1 to 3.3.1
  Pipfile.lock
Labels: approved, bot

#931 Adding sesheta as a maintainer
  .thoth.yaml
Labels: approved

#933 Release of version 0.6.3
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: bot

#935 Automatic update of dependency thoth-storages from 0.23.2 to 0.24.0
  Pipfile.lock
Labels: approved, bot

#937 Release of version 0.6.4
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot

#938 User-API response requires string not enum
  thoth/user_api/api_v1.py
Labels: approved

#940 Automatic update of dependency thoth-common from 0.13.12 to 0.13.13
  Pipfile.lock
Labels: approved, bot

#942 Release of version 0.6.5
  CHANGELOG.md
  thoth/user_api/__init__.py
Labels: approved, bot

#943 switching to pre-commit
  .coafile
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  gunicorn.conf.py
  thoth/user_api/__init__.py
  thoth/user_api/api_v1.py
  thoth/user_api/image.py
  thoth/user_api/openapi_server.py
  thoth/user_api/payload_filter.py
Labels: approved

#945 Invalid credentials are a special type of image error
  thoth/user_api/api_v1.py
Labels: approved, size/XS
