Repository thoth-station/user-api, pull requests merged in 2021-11, with the labels that each got.

#1504 Drop hardware endpoint
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/L

#1507 updating to https routes for pre-commit
  .pre-commit-config.yaml
Labels: approved, size/XS

#1508 Adjust output type for /python/imports endpoint
  openapi/openapi.yaml
Labels: approved, size/S

#1512 Update base image
  .aicoe-ci.yaml
Labels: approved, size/XS

#1506 Drop /s2i/python endpoint and promote container images endpoint
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/L

#1517 Use distinct in import name endpoint
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#1520 Show an example with a matching import
  openapi/openapi.yaml
Labels: approved, size/S
