Repository thoth-station/user-api, pull requests merged in 2021-12, with the labels that each got.

#1529 Expose endpoint listing available environments
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M

#1535 Fix return type for listing environments
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#1549 Extend parameters provided by list containers endpoint
  openapi/openapi.yaml
Labels: approved, size/XS

#1553 Add my username to reviewers
  OWNERS
Labels: approved, size/XS

#1542 Parametrize obtaining container images
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M

#1547 List available Python versions for environments
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/S

#1550 Provide an endpoint for listing environments used to solve a package
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M

#1556 [DONOTMERGE] Testing new endpoints
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: size/M, do-not-merge/work-in-progress

#1557 Fix a bug in openapi schema
  openapi/openapi.yaml
Labels: approved, size/XS

#1558 Environment is not mandatory when querying Python package versions
  openapi/openapi.yaml
Labels: approved, size/XS

#1563 Fix listing of images
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#1548 List available Python packages
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M

#1562 Introduce endpoint for obtaining Python package metadata
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/L

#1566 WIP: Introduce endpoint for obtaining Python package metadata
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: size/L, do-not-merge/work-in-progress
