Repository thoth-station/user-api, pull requests merged in 2021-04, with the labels that each got.

#1363 Drop any metadata associated with the request when providing results
  thoth/user_api/api_v1.py
Labels: approved, lgtm, size/S

#1366 Remove unused function
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#1350 Introduce cache hit metric
  thoth/user_api/api_v1.py
Labels: approved, size/M

#1368 Provide information about queued analyses on status endpoints
  thoth/user_api/api_v1.py
Labels: approved, size/M

#1369 Move metrics creation
  Pipfile
  Pipfile.lock
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
  thoth/user_api/openapi_server.py
Labels: approved, size/XL

#1365 Do not provide objects as query parameters
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, lgtm, size/M

#1373 Do cache hit only for accepted requests
  thoth/user_api/openapi_server.py
Labels: approved, size/XS

#1372 Generalize _send_schedule_message method to consider authentication
  thoth/user_api/api_v1.py
  thoth/user_api/metrics.py
  thoth/user_api/openapi_server.py
Labels: approved, size/L

#1377 Remove input for post_provenance
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#1378 Check if analysis_id is present in after_request logic
  thoth/user_api/openapi_server.py
Labels: approved, size/XS

#1379 Manipulate with cache metrics only if no force was supplied
  thoth/user_api/openapi_server.py
Labels: approved, size/XS

#1382 Add unauthorized reponse schema
  openapi/openapi.yaml
Labels: approved, size/S

#1386 Remove check on force from after_request
  thoth/user_api/openapi_server.py
Labels: approved, size/XS

#1390 Kebechet metadata is no longer query parameter
  thoth/user_api/api_v1.py
Labels: approved, lgtm, size/XS

#1394 Remove old comment
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#1396 Remove unused dev dependencies
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#1398 Fix internal error HTTP status code when exception reporting is on
  thoth/user_api/openapi_server.py
Labels: approved, size/S

#1397 Accept constraints on advise endpoint
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/S

#1408 metric fix
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .pre-commit-config.yaml
  .prow.yaml
  pyproject.toml
  thoth/user_api/openapi_server.py
Labels: approved, size/M
