Repository thoth-station/user-api, pull requests merged in 2021-01, with the labels that each got.

#1169 Bump black version
  .pre-commit-config.yaml
Labels: approved, size/XS

#1115 gitignore and pre-commit updates
  .gitignore
  .pre-commit-config.yaml
Labels: approved, size/S

#1168 Do not propagate message topic in responses
  thoth/user_api/api_v1.py
  thoth/user_api/openapi_server.py
Labels: approved, size/M

#1175 re-locking pipfile lock for typing extension fix
  Pipfile.lock
Labels: approved, size/XS

#1176 Adjust response schema of build analysis endpoint
  openapi/openapi.yaml
Labels: approved, size/S

#1179 Add Kebechet info template
  .github/ISSUE_TEMPLATE/kebechet-info.md
Labels: approved, size/S

#1178 Add Kebechet update template
  .github/ISSUE_TEMPLATE/kebechet_update.md
Labels: approved, size/XS

#1171 Trigger buildlog analysis workflow
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
  thoth/user_api/image.py
Labels: approved, size/L

#1187 Remove legacy build analysis result endpoints
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M

#1195 update to latest messaging
  Pipfile
  Pipfile.lock
  thoth/user_api/api_v1.py
Labels: approved, size/L

#1198 Fix new lines in the example input
  openapi/openapi.yaml
Labels: approved, size/XS

#1199 Allow nullable responses in post-build endpoint
  openapi/openapi.yaml
Labels: approved, size/XS

#1205 updates from the template project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, bot, size/XS

#1206 Expose schema metric
  thoth/user_api/openapi_server.py
Labels: approved, size/S

#1210 Add maintainer
  .thoth.yaml
Labels: approved, size/XS

#1212 Extend configuration to capture versions of other libraries
  openapi/openapi.yaml
Labels: approved, size/S

#1215 Set 1 by default when the revision is up
  thoth/user_api/openapi_server.py
Labels: approved, size/S

#1218 Standardize metric for schema check
  thoth/user_api/configuration.py
  thoth/user_api/openapi_server.py
Labels: approved, size/XS
