Repository thoth-station/user-api, pull requests merged in 2021-06, with the labels that each got.

#1421 Fix module not found error for flask._compat
  Pipfile
  Pipfile.lock
Labels: approved, size/M

#1426 Obtain logs from Ceph as Argo Workflows places them there
  thoth/user_api/api_v1.py
Labels: approved, size/M

#1427 Introduce labels on advise endpoint
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#1432 updates from the template project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, bot, size/XS

#1437 Adjust copyright in headers
  thoth/user_api/api_v1.py
  thoth/user_api/configuration.py
  thoth/user_api/exceptions.py
  thoth/user_api/image.py
  thoth/user_api/openapi_server.py
  thoth/user_api/payload_filter.py
Labels: approved, size/S

#1439 updates from the template project
  .github/ISSUE_TEMPLATE/major-release.md
  .github/ISSUE_TEMPLATE/minor-release.md
  .github/ISSUE_TEMPLATE/patch-release.md
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
Labels: approved, bot, size/S

#1442 update to pydantic calling convention for messaging
  Pipfile
  Pipfile.lock
  thoth/user_api/api_v1.py
Labels: approved, lgtm, size/L

#1452 set badges for easy access to content
  README.rst
Labels: approved, size/S

#1455 flush all pending messages
  thoth/user_api/api_v1.py
Labels: approved, size/M

#1459 Remove qeb-hwt endpoint
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, lgtm, size/M
