Repository thoth-station/user-api, pull requests merged in 2021-07, with the labels that each got.

#1464 remove github app parameters
  Pipfile.lock
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M

#1470 updates from the template project
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .pre-commit-config.yaml
  .prow.yaml
Labels: approved, bot, lgtm, size/S

#1473 Make pre-commit happy
  thoth/user_api/api_v1.py
  thoth/user_api/exceptions.py
  thoth/user_api/image.py
Labels: approved, lgtm, size/M

#1476 Expose cache expiration configuration
  thoth/user_api/openapi_server.py
Labels: approved, size/XS

#1477 Fix import statement
  thoth/user_api/api_v1.py
Labels: approved, size/XS

#1457 initialize producer in similar way to database
  thoth/user_api/api_v1.py
  thoth/user_api/openapi_server.py
Labels: approved, size/S

#1485 fix the exception name from thoth.common
  thoth/user_api/api_v1.py
Labels: approved, size/XS
