Repository thoth-station/user-api, pull requests merged in 2022-01, with the labels that each got.

#1575 Remove Ceph listing methods no longer used
  thoth/user_api/api_v1.py
Labels: approved, size/S

#1578 Some of the items in /container-images response can be nullable
  openapi/openapi.yaml
Labels: approved, size/XS

#1576 Fix typing for endpoint methods
  thoth/user_api/api_v1.py
Labels: approved, size/L

#1577 Pagination fixes and improvements
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
  thoth/user_api/openapi_server.py
Labels: approved, size/L, lgtm

#1591 Rename import to package_import as it causes issues on client
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/S

#1593 State also UBI environments in the environments listing
  thoth/user_api/api_v1.py
Labels: approved, size/S

#1596 openapi-schema-validator <0.2.0 to fix jsonschema version incompatibi…
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#1603 Expose access control headers
  thoth/user_api/openapi_server.py
Labels: approved, size/XS

#1606 Update and polish OpenAPI schema
  .pre-commit-config.yaml
  .yamllint
  openapi/openapi.yaml
  thoth/user_api/openapi_server.py
Labels: size/XXL

#1610 Fix property name
  openapi/openapi.yaml
Labels: approved, size/XS

#1616 Remove unused .thothTemplate.yaml
  .thothTemplate.yaml
Labels: approved, size/S

#1618 Allow nullable requires and entry_points
  openapi/openapi.yaml
Labels: approved, size/XS

#1624 Remove deprecated metadata endpoint
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/L, lgtm

#1628 Add new query parameters for containerized environments to the api
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M

#1637 openapi parameter schema default value doesnt take null
  openapi/openapi.yaml
Labels: approved, size/XS
