Repository thoth-station/user-api, pull requests merged in 2022-09, with the labels that each got.

#1804 :guardsman: Update the OWNERS for user-api maintenance
  .pre-commit-config.yaml
  .prow.yaml
  OWNERS
Labels: approved, size/S

#1759 feat: add callbackurl to advise endpoint
  .pre-commit-config.yaml
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: size/L, lgtm

#1802 ​/container-images 404 error code fix
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/S, lgtm

#1806 Add 400 response for api /python/package/versions on Invalid request
  openapi/openapi.yaml
Labels: size/S, lgtm

#1810 Include fallback option for load of kube-config
  thoth/user_api/api_v1.py
Labels: approved, size/S

#1815 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: approved, size/XS, ok-to-test
