Repository thoth-station/user-api, pull requests merged in 2022-03, with the labels that each got.

#1697 Fix the openapi properties for repo-init bit
  openapi/openapi.yaml
Labels: approved, size/S

#1698 Replace yaml anchor with standard swagger property ref
  openapi/openapi.yaml
Labels: approved, size/L

#1702 Downgrade `flask` to `<=1.0.0`
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#1709 Document how to run User API locally
  .env.template
  README.rst
Labels: approved, size/M

#1712 Fix initialize_repo operationId in schema
  openapi/openapi.yaml
Labels: approved, size/XS

#1717 Adjust OpenAPI spec to fix serialization issues
  openapi/openapi.yaml
Labels: approved, size/XS

#1718 Removed the deprecated flask_script
  Pipfile
  Pipfile.lock
  openapi/openapi.yaml
  thoth/user_api/openapi_server.py
Labels: approved, size/L

#1722 Add Thoth Search UI URL to response headers
  openapi/openapi.yaml
  thoth/user_api/openapi_server.py
Labels: approved, size/M

#1735 Revert to `click==8.0.4` in pre-commit config
  .pre-commit-config.yaml
Labels: approved, size/XS

#1691 added ordering to python versions endpoint
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M

#1729 Report an error if solver document is missing
  thoth/user_api/api_v1.py
Labels: approved, size/S
