Repository thoth-station/user-api, pull requests merged in 2022-05, with the labels that each got.

#1751 Fix default value for imported packages
  openapi/openapi.yaml
Labels: approved, size/XS, lgtm

#1750 Return 400 error when no package found
  thoth/user_api/api_v1.py
Labels: approved, size/S

#1747 Automatic update of base-image in CI
  .aicoe-ci.yaml
Labels: approved, size/XS, ok-to-test

#1757 Fix default advise python version and example analysis_id
  openapi/openapi.yaml
Labels: approved, size/XS

#1760 Fix default marker_evaluation_result value in package dependencies endpoint
  openapi/openapi.yaml
Labels: approved, size/XS
