Repository thoth-station/user-api, pull requests merged in 2022-02, with the labels that each got.

#1641 Add myself to maintainers
  .thoth.yaml
Labels: approved, size/XS

#1631 New module release in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, size/XS, lgtm

#1657 Update base image version to latest
  .aicoe-ci.yaml
Labels: approved, size/XS

#1662 Fix mercator OpenAPI schema
  openapi/openapi.yaml
Labels: approved, size/XS

#1663 Add missing items in the OpenAPI spec
  openapi/openapi.yaml
Labels: approved, size/XS

#1666 Fix NotFoundExceptionError
  thoth/user_api/exceptions.py
Labels: approved, size/XS

#1669 Change default environment values for package metadata
  openapi/openapi.yaml
Labels: approved, size/XS

#1676 Modify skopeo OpenAPI schema
  openapi/openapi.yaml
Labels: approved, size/M

#1681 Downgrade markupsafe dependency < 2.1.0
  Pipfile
  Pipfile.lock
Labels: approved, size/L

#1687 Fix typo in OpenAPI schema
  openapi/openapi.yaml
Labels: approved, size/XS

#1671 added url return params
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/S

#1526 add endpoint for repo-init workflow
  openapi/openapi.yaml
  thoth/user_api/api_v1.py
Labels: approved, size/M
